language: java
services:
  - mysql
jdk:
  - openjdk11
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE payment_portal;'
